version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"  # Expose le port 5252 pour Flask
    container_name: softy-pinko-back-end

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:80"  # Mappe le port 80 de Nginx vers le port 9000 de l'hôte
    container_name: softy-pinko-front-end
    depends_on:
      - back-end  # S'assure que le back-end démarre avant le front-end
