# version: '3.8'

# services:
#   back-end:
#     build:
#       context: ./back-end
#       dockerfile: Dockerfile
#     ports:
#       - "5252:5252"  # Expose le port 5252 pour Flask
#     container_name: softy-pinko-back-end

#   front-end:
#     build:
#       context: ./front-end
#       dockerfile: Dockerfile
#     ports:
#       - "9000:80"  # Mappe le port 80 de Nginx vers le port 9000 de l'hôte
#     container_name: softy-pinko-front-end
#     depends_on:
#       - back-end  # S'assure que le back-end démarre avant le front-end

# version: '3.8'

# services:
#   back-end:
#     build:
#       context: ./back-end
#       dockerfile: Dockerfile
#     image: softy-pinko-back-end
#     expose:
#       - "5252"  # Expose le port interne pour le proxy
#     container_name: back-end

#   front-end:
#     build:
#       context: ./front-end
#       dockerfile: Dockerfile
#     image: softy-pinko-front-end
#     expose:
#       - "9000"  # Expose le port interne pour le proxy
#     container_name: front-end

#   proxy:
#     build:
#       context: ./proxy
#       dockerfile: Dockerfile
#     image: softy-pinko-proxy
#     ports:
#       - "80:80"  # Mappe le port 80 du conteneur au port 80 de l'hôte
#     depends_on:
#       - back-end
#       - front-end
#     container_name: proxy

version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end
    expose:
      - "5252"
    # container_name: back-end
    deploy:
      replicas: 2  # Number of API server instances
      restart_policy:
        condition: on-failure

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end
    expose:
      - "9000"
    # container_name: front-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy
    ports:
      - "80:80"  # Map port 80 on host to port 80 on the proxy
    depends_on:
      - back-end
      - front-end
    # container_name: proxy

